# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1c6012b291fd141412bfb7b40511b0a33b9a3209d5766fde2ab9c970d4e63f5d5e0cb8c872aa13c187efa6194deb10158091c9b79bf52c45e9acb07f02224a09

test:
  secret_key_base: 94c4aefc98c12261771db0938c6475b1667834b60705b9ed49d111dc84d1e52a97816fd461cde18f2937c786460d16ae4aad2c54f00698a15e78d2af5b0899dd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
